### PR TITLE
V1.30

### PR DESCRIPTION
**Pull request by Deepfreeze32**
Merging in V1.30 work to master for release.

### CODE REVIEW

**Comment by Deepfreeze32** [comment]
Oops! Wanted to preview this, didn't mean to accidentally do this! my bad

**Comment by harrowm** [comment]
Wow.  You have been busy !
Do you want to submit a pr or shall I make you a collaborator or do you want to host yourself and I can post a message on my repo ?

Regards
Malcolm

**Comment by Deepfreeze32** [comment]
If it's not a large hassle, I feel like maybe making me a collaborator would be the best solution. I noticed that due to SEO inertia and the existing links on stardot and atomulator.acornatom.co.uk, it looks like most references to this project point to this repository, so it would make more sense to leverage that existing set of references, I think.

**Comment by harrowm** [comment]
Hopefully you got an invite email.  Let me know if not ..

**Comment by Deepfreeze32** [comment]
Just clicked on it, and GitHub now says I have push permissions. Thanks! I’ll merge in my changes when I get some time today.

**Pull request closed without merging**
